using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Data.SqlClient;
using System.Data;

namespace JournalProject
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {

        public MainWindow()
        {
            InitializeComponent();
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {

            string connectionString = ConfigurationManager.ConnectionStrings["JournalDBProduction"].ConnectionString;

            using (SqlConnection connection = new SqlConnection(connectionString))
            {

                try
                {
                    connection.Open();
                    string sql = "SELECT * FROM articles";
                    SqlCommand command = new SqlCommand(sql, connection);
                    SqlDataAdapter sda = new SqlDataAdapter(command);
                    DataTable dt = new DataTable("authors");
                    sda.Fill(dt);
                    dataGrid1.ItemsSource = dt.DefaultView;
                    authorsArticles.ItemsSource = dt.DefaultView;

                    string sql2 = "SELECT * FROM journals";
                    SqlCommand command2 = new SqlCommand(sql2, connection);
                    SqlDataAdapter sda2 = new SqlDataAdapter(command2);
                    DataTable dt2 = new DataTable("journals");
                    sda2.Fill(dt2);
                    journalDataGrid.ItemsSource = dt2.DefaultView;

                    string sql3 = "SELECT * FROM articles WHERE journal_id=1 ORDER BY page_start";
                    SqlCommand command3 = new SqlCommand(sql3, connection);
                    SqlDataAdapter sda3 = new SqlDataAdapter(command3);
                    DataTable dt3 = new DataTable("articles");
                    sda3.Fill(dt3);
                    issueDataGrid.ItemsSource = dt3.DefaultView;

                    string sql4 = "SELECT * FROM authors";
                    SqlCommand command4 = new SqlCommand(sql4, connection);
                    SqlDataAdapter sda4 = new SqlDataAdapter(command4);
                    DataTable dt4 = new DataTable("authors");
                    sda4.Fill(dt4);
                    dataGrid2.ItemsSource = dt4.DefaultView;
                    articleAuthors.ItemsSource = dt4.DefaultView;
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Database connection Error: " + ex.Message);
                }
            }
        }

        private void articleAuthors_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }
    }
}
